### ISSUE TITLE
.env.example file is missing

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#1]
Please include the .env.example file

**Comment by Raza9798** [comment]
please resolve this and let me know @axnish27

**Comment by axnish27** [comment]
env.example file included

**Comment by Raza9798** [comment]
once the issue is resolved close it by clicking the close button here after. and make sure to mention me on comments so I will be notified @axnish27

**Comment by axnish27** [comment]
okay sure @Raza9798
