### ISSUE TITLE
fix datatable search

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#20]
![image](https://github.com/user-attachments/assets/1c3d12d9-c020-48f6-aa3b-318b170e3434)

**Comment by axnish27** [comment]
okay sure @Raza9798

**Comment by axnish27** [comment]
issue is fixed and created a pr please check @Raza9798  #24

**Comment by Raza9798** [comment]
https://github.com/axnish27/employee-profile-manager/pull/24#discussion_r1759566199 requested information
