### ISSUE TITLE
fix update the relationship information

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#31]
Unable to update the relationship information

![image](https://github.com/user-attachments/assets/a0364fa4-80b5-4817-a6e1-9e9a768b2131)
![image](https://github.com/user-attachments/assets/0e0fec82-b512-4c1d-8781-52c552468ebb)

_Originally posted by @Raza9798 in https://github.com/axnish27/employee-profile-manager/issues/30#issuecomment-2361914572_

**Comment by axnish27** [comment]
Ill improve the Create and Update to work with Relationship @Raza9798

**Comment by Raza9798** [comment]
Requested multiple changes https://github.com/axnish27/employee-profile-manager/pull/32

**Comment by axnish27** [comment]
> Requested multiple changes #32

Okay ill make the requested changes @Raza9798 #32

**Comment by axnish27** [comment]
> Requested multiple changes #32
 
Requested changes have been made please review again @Raza9798  #32
