### ISSUE TITLE
Fix relationship field on CRUD

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#33]
when editing data the relationship field get duplicate. check this and fix it

![image](https://github.com/user-attachments/assets/648afbd2-e6b1-497e-89b9-b241237f34f6)

_Originally posted by @Raza9798 in https://github.com/axnish27/employee-profile-manager/issues/32#issuecomment-2369351115_

**Comment by axnish27** [comment]
fixed and created a pull req please check @Raza9798  #35

**Comment by Raza9798** [comment]
requested changes https://github.com/axnish27/employee-profile-manager/pull/35 @axnish27
