### ISSUE TITLE
company page rendering fix

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#37]
![image](https://github.com/user-attachments/assets/12a2926c-0c4a-44d6-ad5b-aa91af56162d)

fix the UI and display it properly on a datatable

**Comment by axnish27** [comment]
Okay sure ill implement a new UI with data Table

**Comment by axnish27** [comment]
Implemented a new UI with data displayed in Data table and all other CRUD functionalities
PR #43 
Please review @Raza9798

**Comment by Raza9798** [comment]
unable to delete a company fix it
