### ISSUE TITLE
fix unable to delete a company

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#45]
unable to delete a company fix it

_Originally posted by @Raza9798 in https://github.com/axnish27/employee-profile-manager/issues/37#issuecomment-2372467069_

**Comment by axnish27** [comment]
https://github.com/user-attachments/assets/de41e7b6-50c1-4aad-8cc1-38962bc2273d

Deleting a Company works fine please check after migrate:fresh  cuz i changed some migration to make delete function work @Raza9798

**Comment by Raza9798** [comment]
after migration it is working @axnish27
