### ISSUE TITLE
toasts notification integration

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#46]
use toasts notification to render success message and error message

reference https://getbootstrap.com/docs/5.3/components/toasts/#live-example

**Comment by axnish27** [comment]
Okay sure ill use toast to render success error messages

**Comment by axnish27** [comment]
As per the instructions toast notifications implemented and created a PR #55  @Raza9798

**Comment by Raza9798** [comment]
the message should be send from backend to frontend. you have to display that message in toasts. show the message dynamically

**Comment by axnish27** [comment]
![image](https://github.com/user-attachments/assets/6243e100-09d7-401b-bb3c-c75e0f569445)
![image](https://github.com/user-attachments/assets/cb2daa4e-b174-431d-a809-d3e61193c343)
![image](https://github.com/user-attachments/assets/77a37220-05fe-427f-b07f-6ad94c91ef46)

i think thats the way i have implemented can you please check again..for your reference i have attached the code snippets @Raza9798

**Comment by Raza9798** [comment]
you have to pass which company was deleted and and which data was updated. @axnish27

**Comment by axnish27** [comment]
> you have to pass which company was deleted and and which data was updated. @axnish27

Ah okay understood...ill improve the implementation

**Comment by axnish27** [comment]
As per the instructions better responses have been implemented please review again #55 @Raza9798

**Comment by Raza9798** [comment]
Once we delete a company it removes the all users who are belong to that specific company. that should not be happen in our systems.
