### ISSUE TITLE
remove alter migrations integrate with its base migration file

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#48]
remove all of the migration alternates and integrate it with single table schema  
![image](https://github.com/user-attachments/assets/f3fdc0a1-2959-4573-bdbe-67e1e5b5c89c)
![image](https://github.com/user-attachments/assets/a99ff1e3-6ad0-4935-abc3-6e9e03de14a3)

**Comment by axnish27** [comment]
Removed alter migrations and created a PR #51 please check
