### ISSUE TITLE
refactor the controller method and wrap with try catch

### ISSUE THREAD

**Issue by Raza9798** [axnish27/employee-profile-manager#49]
I noticed you have added the try catch only for validation parts. please wrap entire method with try catch. the way you done was not acceptable.

![image](https://github.com/user-attachments/assets/ecb69f09-03b2-4656-ba3c-e825e4b8f3a8)

**Comment by axnish27** [comment]
Wrapped entire controller method in a try Block and created a PR please check @Raza9798 #52
